# -*- coding: utf-8 -*-
"""buoi3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjykm29pRZ66Y4_yF1c4eaOtXha_0CrH
"""

#1
n = int(input())
def daoso(n):
  A=""
  while n != 0:
    A=A+str(n%10)
    n=n//10
  return int(A)
print(daoso(n))

#2
a,b = map(int,input("nhập 2 số : ").split())
a = a^b
b = a^b
a = a^b
print(a,b)

#3
n = int(input("nhập số n : "))
if n & (n-1) == 0:
  print(True)
else:
  print(False)
#vd
#n=8 => n = 1000
#n-1=7 => n = 0111

#4
m,n = map(int,input("nhập m và n : ").split())
print(m//n)

#5
import math
m,n = map(int,input("nhập m và n : ").split())
print(math.ceil(m/n))

#even and odd
n = int(input("nhập n : "))
if n%2 == 0:
  print("Even")
else:
  print("Odd")

#Check negative numbers
a,b = map(int,input().split())
if a<0 and b<0:
  print("Yes")
else:
  print("No")

#longer string
a,b = input().split()
if len(a)>len(b):
  print("True")
else:
  print("False")

#triangle
a = int(input("nhập cạnh a : "))
b = int(input("nhập cạnh b : "))
c = int(input("nhập cạnh c : "))
if a-b<c and b-c<a and c-a<b:
  print("Yes")
else:
  print("No")

#larget numbers
a = int(input("nhập a : "))
b = int(input("nhập b : "))
c = int(input("nhập c : "))
d = int(input("nhập d : "))
print(max(a,b,c,d))

#phân loại tam giác
a = int(input("nhập cạnh a : "))
b = int(input("nhập cạnh b : "))
c = int(input("nhập cạnh c : "))
if a-b<c and b-c<a and c-a<b:
  if a == b == c:
    print("Tam giác đều")
  elif a != b != c:
    print("tam giác thường")
  else:
    print("tam giác cân5")
else:
  print("Không phải tam giác")

#kiểm tra năm nhuận
n = int(input("nhập năm : "))
if n % 400 == 0:
  print("Yes")
else:
  if n % 4 == 0:
    if n % 100 == 0:
      print("No")
    else:
      print("Yes")
  else:
    print("No")

#Tính tiền điện
n = int(input("nhập số điện : "))
tiendien=0
if n > 50:
  n = n - 50
  tiendien = 1500*50
  if n > 50:
    n = n - 50
    tiendien = tiendien + 2000*50 + 3000*n

  else:
    tiendien += 2000*n
else:
  tiendien = 1500*n
print("tiền điện là : ",tiendien)

#giải phương trình bậc nhất
a=float(input())
b=float(input())
if a == 0:
  if b == 0:
    print("vô số nghiệm")
  else:
    print("vô nghiệm")
else:
  print(f'{(-b/a):.2f}')

#xếp loại học lực
n = float(input())
if n >= 8:
  print("Giỏi")
elif n >= 6.5:
  print("Khá")
elif n >= 5:
  print("Trung bình")
else:
  print("Yếu")

#rounding
n = float(input())
if n%1 == 0:
  print(n,n,n)
else:
  if n >=0 :
    n1=n//1
    n2=n1+1
    if n2 - n > n - n1:
      nk = n1
    else:
      nk = n2
    print(n1,n2,nk)
  else:
    n2=n//1
    n1=n1-1
    if n2 - n > n - n1:
      nk = n2
    else:
      nk = n1
    print(n1,n2,nk)

